/*
 * This source file was generated by the Gradle 'init' task
 */
package github.tkasu.aoc25.challenges

import kotlin.test.Test
import github.tkasu.aoc25.challenges.day1.Part1
import kotlin.test.assertEquals

class Day1Test {
    @Test fun `part1 returns correct answer`() {
        val result = Part1.solveFromResource()
        assertEquals(result, 3)
    }
}
