/*
 * This source file was generated by the Gradle 'init' task
 */
package github.tkasu.aoc25.challenges

import kotlin.test.Test
import github.tkasu.aoc25.challenges.day2.Part1
import github.tkasu.aoc25.challenges.day2.Part2
import kotlin.test.assertEquals

class Day2Test {
    @Test
    fun `part1 returns correct answer`() {
        val result = Part1.solveFromResource()
        assertEquals(1227775554L, result)
    }

    @Test
    fun `part2 returns correct answer`() {
        val result = Part2.solveFromResource()
        assertEquals(4174379265L, result)
    }
}
