/*
 * This source file was generated by the Gradle 'init' task
 */
package github.tkasu.aoc25.challenges

import kotlin.test.Test
import github.tkasu.aoc25.challenges.day3.Part1
import kotlin.test.assertEquals

class Day3Test {
    @Test
    fun `part1 returns correct answer`() {
        val result = Part1.solveFromResource()
        assertEquals(357L, result)
    }

}
