/*
 * This source file was generated by the Gradle 'init' task
 */
package github.tkasu.aoc25.challenges

import kotlin.test.Test
import github.tkasu.aoc25.challenges.day4.Part1
import github.tkasu.aoc25.challenges.day4.Part2
import kotlin.test.assertEquals

class Day4Test {
    @Test
    fun `part1 returns correct answer`() {
        val result = Part1.solveFromResource()
        assertEquals(13, result)
    }

    @Test
    fun `part2 returns correct answer`() {
        val result = Part2.solveFromResource()
        assertEquals(43, result)
    }
}
